# configs/model/diff.yaml
model_name: diff
diff_epochs: 10
patch_size: 16
vit_size: base  # choices: [base, large, huge]
latent_diff: false   # Explicitly set to true for latent diffusion
latent_channels: 3