defaults:
  - model: vae_kl
  - experiment_type: default
  - data: default
  - inference: default
  - _self_

hydra:
  run:
    dir: output/${hydra:runtime.choices.model}${experiment_type.test_suffix}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  # output_subdir: .hydra